name: BetterBuild API
main: net.lax1dude.eaglercraft.v1_8.plugin.gateway_bungeecord.EaglerXBungee
version: 1.0.5
description: Plugin to allow Better Build players to join your network, or allow Better Build players to use your network as a proxy to join other networks
author: Floco
